module.exports = {
  apps: [
    {
      name: 'api-server',
      script: 'dist/server.js',
      cwd: '/app/backend',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        DATABASE_URL: 'file:/app/data/db.sqlite',
        LOGGING_CONFIG_PATH: '/app/backend/logging.json',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      error_file: '/app/logs/api-error.log',
      out_file: '/app/logs/api-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'processing-worker',
      script: 'dist/worker.js',
      cwd: '/app/worker',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'file:/app/data/db.sqlite',
        DATA_DIR: '/app/data',
        MEDIA_PATH: '/app/media',
        API_INTERNAL_URL: 'http://localhost:3000',
        LOGGING_CONFIG_PATH: '/app/worker/logging.json',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/app/logs/worker-error.log',
      out_file: '/app/logs/worker-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};